spring:
    profiles:
        active: dev
    jackson:
        serialization:
            indent_output: true
    security:
        user:
            name: won
            password: won
    redis:
        host: 127.0.0.1
        port: 6379
    datasource: # DB 설정
        tomcat:
            max-active: 50
            max-idle: 20
            min-idle: 15
server:
    port: 8080

app:
    name: DevKotlin
    version: 0.1
    homeUri: /members/
    emailDomain: won@devplay.com
    pathPatternsNotToBeIntercepted:
        - /favicon.ico
        - /assets/**
        - /modules/**
        - /plugins/**
        - /css/**
        - /font/**
        - /img/**
        - /js/**
    dataSource:
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        user: root
        password: devplayg12!@
        minimumIdle: 20
        maximumPoolSize: 20
---

spring:
    profiles:
        active: dev
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    resources:
      cache:
          period: 0

server:
    port: 80

logging:
    level:
        com.devplayg: debug
