spring:
    profiles:
        active: prod
    jackson:
        serialization:
            indent_output: true
    security:
        user:
            name: won
            password: won
    redis:
        host: 127.0.0.1
        port: 6379
#    datasource:
#        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#        username: unisem
#        password: Uniiot12!@
#    jpa:
#        show-sql: false
#        hibernate:
#            ddl-auto: validate
#        open-in-view: false
#    datasourmd
#
# DB 설정
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        tomcat:
#            max-active: 50
#            max-idle: 20
#            min-idle: 15
#        hikari:
#            auto-commit: false
#            maximum-pool-size: 20
#        sql-script-encoding: UTF-8
server:
    port: 8080

app:
    name: DevKotlin
    version: 0.1
    homeUri: /audits/
#    datasource:
#        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#        username:
#        password:
---

spring:
    profiles:
        active: dev
#    datasource:
#        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#        username:
#        password:
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false

server:
    port: 80

logging:
    level:
        com.devplayg: debug
