spring:
    profiles:
        active: prod
    jackson:
        serialization:
            indent_output: true
    security:
        user:
            name: won
            password: won
    redis:
        host: 127.0.0.1
        port: 6379
server:
    port: 8080
    servlet:
        session:
            timeout: 10s
app:
    name: DevKotlin
    version: 0.1
    homeUri: /audits/
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sb201?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: root
        password: devplayg12!@
---

spring:
    profiles:
        active: dev
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false

server:
    port: 80

logging:
    level:
        com.devplayg: debug
